"""update resume schema

Revision ID: 0514c44c8bfc
Revises: e15153046fda
Create Date: 2026-07-19 08:07:47.200470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0514c44c8bfc'
down_revision: Union[str, Sequence[str], None] = 'e15153046fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('resumes', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.add_column('resumes', sa.Column('extracted_text', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'resumes', ['stored_filename'])
    op.drop_column('resumes', 'filename')
    op.drop_column('resumes', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resumes', type_='unique')
    op.drop_column('resumes', 'extracted_text')
    op.drop_column('resumes', 'stored_filename')
    op.drop_column('resumes', 'original_filename')
    # ### end Alembic commands ###
