"""add resume file metadata

Revision ID: e15153046fda
Revises: eb126274f730
Create Date: 2026-07-18 11:57:17.043034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15153046fda'
down_revision: Union[str, Sequence[str], None] = 'eb126274f730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('analyses', sa.Column('feedback', sa.Text(), nullable=False))
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.drop_constraint(op.f('analyses_resume_id_fkey'), 'analyses', type_='foreignkey')
    op.drop_constraint(op.f('analyses_job_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'analyses', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analyses', 'match_score')
    op.drop_column('analyses', 'missing_skills')
    op.drop_column('analyses', 'recommendations')
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.add_column('resumes', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('resumes', sa.Column('file_type', sa.String(length=20), nullable=False))
    op.add_column('resumes', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('resumes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resumes', 'extracted_text')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.add_column('resumes', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_column('resumes', 'created_at')
    op.drop_column('resumes', 'content')
    op.drop_column('resumes', 'file_type')
    op.drop_column('resumes', 'file_path')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.add_column('analyses', sa.Column('recommendations', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('analyses', sa.Column('missing_skills', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('analyses', sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_job_id_fkey'), 'analyses', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('analyses_resume_id_fkey'), 'analyses', 'resumes', ['resume_id'], ['id'])
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_column('analyses', 'feedback')
    op.drop_column('analyses', 'score')
    # ### end Alembic commands ###
